#!/bin/bash -e

kernels=()

while read -r line; do
    if ! read -r pkgbase > /dev/null 2>&1 < "${line%/vmlinuz}/pkgbase"; then
        # if the kernel has no pkgbase, we skip it
        continue
    fi

    kernels+=("/$line")
done

for kernel in "${kernels[@]}"; do
    kernel-install -v remove "$(basename "${kernel%/vmlinuz}")"
done
