#!/bin/bash -e

kernels=()
all=0

while read -r line; do
    if [[ $line != */vmlinuz ]]; then
        # triggers when it's a change to usr/lib/initcpio/*
        all=1
        continue
    fi

    if ! read -r pkgbase > /dev/null 2>&1 < "${line%/vmlinuz}/pkgbase"; then
        # if the kernel has no pkgbase, we skip it
        continue
    fi

    kernels+=("/$line")
done

if (( all )); then
    # change to use all kernels
    kernels=(/usr/lib/modules/*/vmlinuz)
fi

for kernel in "${kernels[@]}"; do
    kernel-install -v add "$(basename "${kernel%/vmlinuz}")" "$kernel"
done
